{
 "title": "Astra - Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "astra-production, astra-staging"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"${namespace}\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Preprocessor incoming vs outgoing bytes",
   "type": "timeseries",
   "description": "(Delete)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"${namespace}\",pod=~\"astra-preprocessor.*\",}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}-out"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"${namespace}\",pod=~\"astra-preprocessor.*\",}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}-in"
    }
   ]
  },
  {
   "title": "Indexer Rollovers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(astra_cluster_name) (increase(rollovers_completed_total{namespace=\"${namespace}\",astra_component=\"index\"}[5m]))",
     "legendFormat": "completed"
    },
    {
     "expr": "sum by(astra_cluster_name) (increase(rollovers_failed_total{namespace=\"${namespace}\", astra_component=\"index\"}[5m]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Recovery nodes size (cached)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(cached_recovery_nodes_size{namespace=\"${namespace}\"})",
     "legendFormat": "cached_recovery_nodes_size"
    }
   ]
  },
  {
   "title": "Recovery tasks created",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(recovery_tasks_created_total{namespace=\"${namespace}\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Recovery tasks count (cached)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "max(cached_recovery_tasks_size{namespace=\"${namespace}\"})",
     "legendFormat": "recovery_tasks_count"
    }
   ]
  },
  {
   "title": "Snapshot count (cached)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max(cached_snapshots_size{namespace=\"${namespace}\"})",
     "legendFormat": "cached_snapshots_size"
    }
   ]
  },
  {
   "title": "Replica count (cached)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "max(cached_replica_nodes_size{namespace=\"${namespace}\"})",
     "legendFormat": "replica_nodes_count"
    }
   ]
  },
  {
   "title": "Cache slots count (cached)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "max(cached_cache_slots_size{namespace=\"${namespace}\"})",
     "legendFormat": "cached_cache_slots_size"
    }
   ]
  },
  {
   "title": "Cache nodes count (cached)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(cached_service_nodes_size{namespace=\"${namespace}\"})",
     "legendFormat": "cached_service_nodes_size"
    }
   ]
  },
  {
   "title": "Live indexer count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (astra_cluster_name) (irate(live_messages_indexed{namespace=\"${namespace}\",astra_component=\"index\"}[1m]) > 0)",
     "legendFormat": "indexeing"
    },
    {
     "expr": "count by (astra_cluster_name) (irate(live_messages_indexed{namespace=\"${namespace}\",astra_component=\"index\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Live records received Per Min",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (irate(live_messages_indexed{namespace=\"${namespace}\", astra_component=\"index\"}[1m]) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indexer exception count",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        { "id": "1", "settings": { "interval": "1000", "min_doc_count": "0" }, "type": "histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "level: ERROR AND project:astra AND namespace: ${namespace} AND container_name: astra-index",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Indexer recovery task restart failure count",
     "type": "timeseries",
     "description": "Number of exceptions when creating recovery tasks",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "bucketAggs": [
        { "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "level: ERROR AND project:astra AND namespace: ${namespace} AND container_name: astra-index AND exception.error_root_cause_class_name:\"com.slack.astra.server.RecoveryTaskCreator.lambda$determineStartingOffset$5(RecoveryTaskCreator.java:154)\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Indexer recovery task NPE count",
     "type": "timeseries",
     "description": "Number of exceptions when creating recovery tasks",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "bucketAggs": [
        { "id": "1", "settings": { "interval": "1000", "min_doc_count": "0" }, "type": "histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "level: ERROR AND project:astra AND namespace: ${namespace} AND container_name: astra-index AND exception.error_root_cause_class_name:\"java.lang.NullPointerException\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Query stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC Request count (query)",
     "type": "timeseries",
     "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namepsace}\", astra_component=\"query\", grpc_status=\"0\"}[1m]))",
       "legendFormat": "grpc_status=ok"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"query\", grpc_status=\"2\"}[1m]))",
       "legendFormat": "grpc_status=unknown_error"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"query\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
       "legendFormat": "grpc_status={{grpc_status}}"
      }
     ]
    },
    {
     "title": "gRPC Request count (indexer)",
     "type": "timeseries",
     "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"index\", grpc_status=\"0\"}[1m]))",
       "legendFormat": "grpc_status=ok"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"index\", grpc_status=\"2\"}[1m]))",
       "legendFormat": "grpc_status=unknown_error"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"index\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
       "legendFormat": "grpc_status={{grpc_status}}"
      }
     ]
    },
    {
     "title": "gRPC Request count (cache)",
     "type": "timeseries",
     "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"cache\", grpc_status=\"0\"}[1m]))",
       "legendFormat": "grpc_status=ok"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"cache\", grpc_status=\"2\"}[1m]))",
       "legendFormat": "grpc_status=unknown_error"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"cache\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
       "legendFormat": "grpc_status={{grpc_status}}"
      }
     ]
    },
    {
     "title": "gRPC Request count (recovery)",
     "type": "timeseries",
     "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"recovery\", grpc_status=\"0\"}[1m]))",
       "legendFormat": "grpc_status=ok"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"recovery\", grpc_status=\"2\"}[1m]))",
       "legendFormat": "grpc_status=unknown_error"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"recovery\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
       "legendFormat": "grpc_status={{grpc_status}}"
      }
     ]
    },
    {
     "title": "gRPC Request count (manager)",
     "type": "timeseries",
     "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "targets": [
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"manager\", grpc_status=\"0\"}[1m]))",
       "legendFormat": "grpc_status=ok"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"manager\", grpc_status=\"2\"}[1m]))",
       "legendFormat": "grpc_status=unknown_error"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"manager\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
       "legendFormat": "grpc_status={{grpc_status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Preprocessor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Preprocessor incoming vs outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (pod) (astra_preprocessor_incoming_docs_total{namespace=\"${namespace}\", astra_component=\"preprocessor\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Preprocessor bulk ingest seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
     "targets": [
      {
       "expr": "max by (pod) (astra_preprocessor_bulk_ingest_seconds_max{namespace=\"${namespace}\", astra_component=\"preprocessor\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Preprocessor producer outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum by(instance) (increase(kafka_producer_outgoing_byte_total{namespace=\"${namespace}\"}[1m]) / 60)",
       "legendFormat": "{{replicaset}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Preprocessor CPU",
     "type": "timeseries",
     "description": "Using 6 cores.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum((rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",pod=~\".*preprocessor.*\"}[1m]) / 60))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Preprocessor Memory",
     "type": "timeseries",
     "description": "8Gi memory calculations",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (pod_set) (label_replace(avg by(pod) (container_memory_usage_bytes{namespace=\"${namespace}\", pod=~\".+-preprocessor.+\", container=~\".+-preprocessor?.+\"}),  \"pod_set\", \"$1\", \"pod\", \"(astra)-preprocessor-(.*)-prod-(.*)\"))",
       "legendFormat": "{{pod_set}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indexer Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Chunk Doc Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance) (max_over_time(live_messages_indexed{namespace=\"${namespace}\", astra_component=\"index\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current Chunk Raw Bytes Size (ingest)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(instance) (max_over_time(live_bytes_indexed{namespace=\"${namespace}\",astra_component=\"index\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current Chunk Raw Bytes Size (directory)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(instance) (max_over_time(live_bytes_dir{namespace=\"${namespace}\",astra_component=\"index\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "gRPC Request count",
     "type": "timeseries",
     "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"index\", grpc_status=\"0\"}[1m]))",
       "legendFormat": "grpc_status=ok"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"index\", grpc_status=\"2\"}[1m]))",
       "legendFormat": "grpc_status=unknown_error"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"index\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
       "legendFormat": "grpc_status={{grpc_status}}"
      }
     ]
    },
    {
     "title": "gRPC Request count",
     "type": "timeseries",
     "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "targets": [
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"index\", grpc_status=\"0\"}[1m]))",
       "legendFormat": "grpc_status=ok"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"index\", grpc_status=\"2\"}[1m]))",
       "legendFormat": "grpc_status=unknown_error"
      },
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"index\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
       "legendFormat": "grpc_status={{grpc_status}}"
      }
     ]
    },
    {
     "title": "Index lag max (# records)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "max by (pod) (kafka_consumer_fetch_manager_records_lag_max{namespace=\"${namespace}\", astra_component=\"index\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Most/least lagged Index (# records)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "targets": [
      {
       "expr": "topk(5, max by (pod) (kafka_consumer_fetch_manager_records_lag_max{namespace=\"${namespace}\",astra_component=\"index\"}))",
       "legendFormat": "__auto"
      },
      {
       "expr": "bottomk(5, max by (pod) (kafka_consumer_fetch_manager_records_lag_max{namespace=\"${namespace}\",astra_component=\"index\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunk Evictions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(increase(chunk_eviction_timer_seconds_count{successful=\"true\", namespace=\"${namespace}\"}[5m]))",
       "legendFormat": "Success Evict"
      },
      {
       "expr": "sum(increase(chunk_eviction_timer_seconds_count{successful=\"false\", namespace=\"${namespace}\"}[5m]))",
       "legendFormat": "Fail Evict"
      }
     ]
    },
    {
     "title": "Chunk Assignments",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sum(increase(chunk_assignment_timer_seconds_count{successful=\"true\", namespace=\"${namespace}\"}[5m]))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(increase(chunk_assignment_timer_seconds_count{successful=\"false\", namespace=\"${namespace}\"}[5m]))",
       "legendFormat": "Fail"
      }
     ]
    },
    {
     "title": "gRPC Request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"cache\"}[1m]))",
       "legendFormat": "grpc_status={{grpc_status}}"
      }
     ]
    },
    {
     "title": "gRPC Request Time ( seconds )",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
     "targets": [
      {
       "expr": "sum by(instance) (max_over_time(grpc_service_request_duration_seconds{http_status=\"200\",namespace=\"${namespace}\", astra_component=\"cache\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replica Assignments",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 113 },
     "targets": [
      {
       "expr": "sum by (replicaset) (increase(replica_assign_succeeded_total{namespace=\"${namespace}\"}[5m]))",
       "legendFormat": "replica_assign_succeeded-{{replicaset}}"
      },
      {
       "expr": "sum by (replicaset) (increase(replica_assign_insufficient_capacity_total{namespace=\"${namespace}\"}[5m]))",
       "legendFormat": "replica_assign_insufficient_capacity-{{replicaset}}"
      }
     ]
    },
    {
     "title": "Replica Evictions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 113 },
     "targets": [
      {
       "expr": "sum by (replicaset) (increase(replica_mark_evict_succeeded_total{namespace=\"${namespace}\"}[5m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum by (replicaset) (increase(replica_mark_evict_failed_total{namespace=\"${namespace}\"}[5m]))",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Replica Assignment Capacity",
     "type": "timeseries",
     "description": "Available slots over time, positive is surplus capacity negative is insufficient capacity",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 113 },
     "targets": [
      {
       "expr": "sum by (replicaset) (sum_over_time(replica_assign_available_capacity{namespace=\"${namespace}\",astra_component=\"manager\"}[1m]) / count_over_time(replica_assign_available_capacity{namespace=\"${namespace}\",astra_component=\"manager\"}[1m]))",
       "legendFormat": "replica_assign_available_capacity"
      }
     ]
    },
    {
     "title": "Snapshot Delete",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
     "targets": [
      {
       "expr": "sum by (replicaset) (increase(snapshot_delete_success_total{namespace=\"${namespace}\", astra_component=\"manager\"}[1m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum by (replicaset) (increase(snapshot_delete_failed_total{namespace=\"${namespace}\", astra_component=\"manager\"}[1m]))",
       "legendFormat": "failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Query nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC Request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 129 },
     "targets": [
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{namespace=\"${namespace}\", astra_component=\"query\"}[1m]))",
       "legendFormat": "grpc_status={{grpc_status}}"
      }
     ]
    },
    {
     "title": "gRPC Request Time ( seconds )",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 129 },
     "targets": [
      {
       "expr": "sum by(instance) (max_over_time(grpc_service_request_duration_seconds{http_status=\"200\",namespace=\"${namespace}\", astra_component=\"query\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Blocking Task Executor Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 129 },
     "targets": [
      {
       "expr": "sum by(instance) (max_over_time(armeria_executor_pool_size_threads{namespace=\"${namespace}\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Recovery nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recovery status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 138 },
     "targets": [
      {
       "expr": "sum(recovery_node_assignment_failed_total{namespace=\"${namespace}\",astra_component=\"recovery\"})",
       "legendFormat": "failed"
      },
      {
       "expr": "sum(recovery_node_assignment_received_total{namespace=\"${namespace}\",astra_component=\"recovery\"})",
       "legendFormat": "received"
      },
      {
       "expr": "sum(recovery_node_assignment_success_total{namespace=\"${namespace}\",astra_component=\"recovery\"})",
       "legendFormat": "success"
      }
     ]
    },
    {
     "title": "Current Chunk Doc Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance) (max_over_time(live_messages_indexed{namespace=\"${namespace}\", astra_component=\"recovery\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current Chunk Raw Bytes Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(instance) (max_over_time(live_bytes_indexed{namespace=\"${namespace}\",astra_component=\"recovery\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Recovery Nodes Records Received",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(records_received_total{namespace=\"${namespace}\", astra_component=\"recovery\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Recovery Rollovers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(astra_cluster_name) (increase(rollovers_completed_total{namespace=\"${namespace}\",astra_component=\"recovery\"}[5m]))",
       "legendFormat": "recovery-completed"
      },
      {
       "expr": "sum by(astra_cluster_name) (increase(rollovers_failed_total{namespace=\"${namespace}\",astra_component=\"recovery\"}[5m]))",
       "legendFormat": "recover-failed"
      }
     ]
    },
    {
     "title": "Active recovery node count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count (max_over_time(live_messages_indexed{namespace=\"${namespace}\", astra_component=\"recovery\"}[1m]) > 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Zookeeper Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metadatastore failures by component",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 114 },
     "targets": [
      {
       "expr": "sum by (astra_component) (rate(metadata_failed_total{namespace=\"${namespace}\"}[1m]))",
       "legendFormat": "{{astra_component}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Memory Usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(irate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", container=~\"astra-?.+\"}[1m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average CPU Time by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "avg(irate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", container=~\"astra-?.+\"}[1m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Network Bytes by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(irate(container_network_transmit_packets_total{namespace=\"${namespace}\"}[1m])) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(irate(container_network_receive_bytes_total{namespace=\"${namespace}\"}[1m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg PPS by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(irate(container_network_transmit_packets_total{namespace=\"${namespace}\"}[1m])) by (pod)",
       "legendFormat": "tx {{pod}}"
      },
      {
       "expr": "avg(irate(container_network_transmit_packets_total{namespace=\"${namespace}\"}[1m])) by (pod)",
       "legendFormat": "rx {{pod}}"
      }
     ]
    },
    {
     "title": "Total PPS by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"${namespace}\"}[1m])) by (pod)",
       "legendFormat": "tx {{pod}}"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"${namespace}\"}[1m])) by (pod)",
       "legendFormat": "rx {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Pause",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_max{namespace=\"${namespace}\",  pod=~'astra-.*'}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}