{
 "title": "KalDB Service",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(system_cpu_usage{}, kaldb_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"kaldb.+${cluster}.+\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Preprocessor incoming vs outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(kaldb_cluster_name)  (increase(kafka_producer_outgoing_byte_total{kaldb_cluster_name=\"$cluster\",container=\"kaldb-preprocessor\"}[1m]) / 60) ",
     "legendFormat": "out"
    },
    {
     "expr": "sum by(kaldb_cluster_name) (increase(kafka_consumer_incoming_byte_total{kaldb_cluster_name=\"$cluster\",container=\"kaldb-preprocessor\"}[1m]) / 60)",
     "legendFormat": "in"
    }
   ]
  },
  {
   "title": "Indexer Rollovers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(kaldb_cluster_name) (increase(rollovers_completed_total{kaldb_cluster_name=\"$cluster\",kaldb_component=\"index\"}[5m]))",
     "legendFormat": "completed"
    },
    {
     "expr": "sum by(kaldb_cluster_name) (increase(rollovers_failed_total{kaldb_cluster_name=\"$cluster\",kaldb_component=\"index\"}[5m]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Recovery nodes size (cached)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(cached_recovery_nodes_size{kaldb_cluster_name=\"${cluster}\"})",
     "legendFormat": "cached_recovery_nodes_size"
    }
   ]
  },
  {
   "title": "Recovery tasks created",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(recovery_tasks_created_total{kaldb_cluster_name=\"${cluster}\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Recovery tasks count (cached)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "max(cached_recovery_tasks_size{kaldb_cluster_name=\"${cluster}\"})",
     "legendFormat": "recovery_tasks_count"
    }
   ]
  },
  {
   "title": "Snapshot count (cached)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max(cached_snapshots_size{kaldb_cluster_name=\"${cluster}\"})",
     "legendFormat": "cached_snapshots_size"
    }
   ]
  },
  {
   "title": "Replica count (cached)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "max(cached_replica_nodes_size{kaldb_cluster_name=\"${cluster}\"})",
     "legendFormat": "replica_nodes_count"
    }
   ]
  },
  {
   "title": "Cache slots count (cached)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "max(cached_cache_slots_size{kaldb_cluster_name=\"${cluster}\"})",
     "legendFormat": "cached_cache_slots_size"
    }
   ]
  },
  {
   "title": "Cache nodes count (cached)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(cached_service_nodes_size{kaldb_cluster_name=\"${cluster}\"})",
     "legendFormat": "cached_service_nodes_size"
    }
   ]
  },
  {
   "title": "Live indexer count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (kaldb_cluster_name) (irate(live_messages_indexed{kaldb_cluster_name=\"$cluster\",kaldb_component=\"index\"}[1m]) > 0)",
     "legendFormat": "indexeing"
    },
    {
     "expr": "count by (kaldb_cluster_name) (irate(live_messages_indexed{kaldb_cluster_name=\"$cluster\",kaldb_component=\"index\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Live records received Per Min",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(kaldb_cluster_name) (irate(live_messages_indexed{kaldb_cluster_name=\"$cluster\",kaldb_component=\"index\"}[1m]) * 60)",
     "legendFormat": "live_messages_indexed"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Indexer exception count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "error_root_cause_class_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host:\"kaldb-index\" AND _exists_:error_stack_trace",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indexer recovery task restart failure count",
   "type": "timeseries",
   "description": "Number of exceptions when creating recovery tasks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host:\"kaldb-index\" AND error_stack_trace:\"com.slack.kaldb.server.RecoveryTaskCreator.lambda$determineStartingOffset$5(RecoveryTaskCreator.java:154)\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indexer recovery task NPE count",
   "type": "timeseries",
   "description": "Number of exceptions when creating recovery tasks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "host:\"kaldb-index\" AND error_root_cause_class_name:\"java.lang.NullPointerException\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Query stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "gRPC Request count (query)",
   "type": "timeseries",
   "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"query\", grpc_status=\"0\"}[1m]))",
     "legendFormat": "grpc_status=ok"
    },
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"query\", grpc_status=\"2\"}[1m]))",
     "legendFormat": "grpc_status=unknown_error"
    },
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"query\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
     "legendFormat": "grpc_status={{grpc_status}}"
    }
   ]
  },
  {
   "title": "gRPC Request count (indexer)",
   "type": "timeseries",
   "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"index\", grpc_status=\"0\"}[1m]))",
     "legendFormat": "grpc_status=ok"
    },
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"index\", grpc_status=\"2\"}[1m]))",
     "legendFormat": "grpc_status=unknown_error"
    },
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"index\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
     "legendFormat": "grpc_status={{grpc_status}}"
    }
   ]
  },
  {
   "title": "gRPC Request count (cache)",
   "type": "timeseries",
   "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"cache\", grpc_status=\"0\"}[1m]))",
     "legendFormat": "grpc_status=ok"
    },
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"cache\", grpc_status=\"2\"}[1m]))",
     "legendFormat": "grpc_status=unknown_error"
    },
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"cache\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
     "legendFormat": "grpc_status={{grpc_status}}"
    }
   ]
  },
  {
   "title": "gRPC Request count (recovery)",
   "type": "timeseries",
   "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"recovery\", grpc_status=\"0\"}[1m]))",
     "legendFormat": "grpc_status=ok"
    },
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"recovery\", grpc_status=\"2\"}[1m]))",
     "legendFormat": "grpc_status=unknown_error"
    },
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"recovery\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
     "legendFormat": "grpc_status={{grpc_status}}"
    }
   ]
  },
  {
   "title": "gRPC Request count (manager)",
   "type": "timeseries",
   "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "targets": [
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"manager\", grpc_status=\"0\"}[1m]))",
     "legendFormat": "grpc_status=ok"
    },
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"manager\", grpc_status=\"2\"}[1m]))",
     "legendFormat": "grpc_status=unknown_error"
    },
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"manager\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
     "legendFormat": "grpc_status={{grpc_status}}"
    }
   ]
  },
  { "title": "Preprocessor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Preprocessor incoming vs outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(kaldb_cluster_name)  (increase(kafka_producer_outgoing_byte_total{kaldb_cluster_name=\"$cluster\"}[1m]) / 60) ",
     "legendFormat": "out"
    },
    {
     "expr": "sum by(kaldb_cluster_name) (increase(kafka_consumer_incoming_byte_total{kaldb_cluster_name=\"$cluster\"}[1m]) / 60)",
     "legendFormat": "in"
    }
   ]
  },
  {
   "title": "Preprocessor lag max (# records)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "expr": "max by (pod) (kafka_consumer_fetch_manager_records_lag_max{kaldb_cluster_name=\"$cluster\", kaldb_component=\"preprocessor\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Most/least lagged Preprocessor (# records)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "topk(5, max by (pod) (kafka_consumer_fetch_manager_records_lag_max{kaldb_cluster_name=\"$cluster\",kaldb_component=\"preprocessor\"}))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "bottomk(5, max by (pod) (kafka_consumer_fetch_manager_records_lag_max{kaldb_cluster_name=\"$cluster\",kaldb_component=\"preprocessor\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Preprocessor CPU",
   "type": "timeseries",
   "description": "Using 6 cores.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"kaldb-preprocessor?.+\",pod=~\".+${cluster}.+\"}[1m]) / 60)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Preprocessor Memory",
   "type": "timeseries",
   "description": "8Gi memory calculations",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pod_set) (label_replace(avg by(pod) (container_memory_usage_bytes{pod=~\"kaldb-preprocessor.+${cluster}.+\", container=~\"kaldb-preprocessor?.+\"}),  \"pod_set\", \"$1\", \"pod\", \"kaldb-preprocessor-(.*)-prod-(.*)\"))",
     "legendFormat": "{{pod_set}}"
    }
   ]
  },
  {
   "title": "Preprocessor producer outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by(instance) (increase(kafka_producer_outgoing_byte_total{kaldb_cluster_name=\"${cluster}\"}[1m]) / 60)",
     "legendFormat": "{{replicaset}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Preprocessor messages dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by (kaldb_cluster_name) (rate(preprocessor_rate_limit_messages_dropped_total{kaldb_cluster_name=\"$cluster\"}[1m]))",
     "legendFormat": "messages"
    }
   ]
  },
  {
   "title": "Preprocessor bytes dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 70 },
   "targets": [
    {
     "expr": "sum by(kaldb_cluster_name) (rate(preprocessor_rate_limit_bytes_dropped_total{kaldb_cluster_name=\"$cluster\"}[1m]))",
     "legendFormat": "{{kaldb_cluster_name}}"
    }
   ]
  },
  {
   "title": "Message Drop Reasons",
   "type": "table",
   "description": "Last 5 mins",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 70 },
   "targets": [
    {
     "expr": "sum by(reason, service) (increase (preprocessor_rate_limit_messages_dropped_total{kaldb_cluster_name=\"$cluster\"}[5m]))"
    }
   ]
  },
  { "title": "Indexer Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Current Chunk Doc Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (max_over_time(live_messages_indexed{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"index\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Chunk Raw Bytes Size (ingest)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (max_over_time(live_bytes_indexed{kaldb_cluster_name=\"$cluster\",kaldb_component=\"index\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Chunk Raw Bytes Size (directory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (max_over_time(live_bytes_dir{kaldb_cluster_name=\"$cluster\",kaldb_component=\"index\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gRPC Request count",
   "type": "timeseries",
   "description": "https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"index\", grpc_status=\"0\"}[1m]))",
     "legendFormat": "grpc_status=ok"
    },
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"index\", grpc_status=\"2\"}[1m]))",
     "legendFormat": "grpc_status=unknown_error"
    },
    {
     "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"index\", grpc_status!=\"2\", grpc_status!=\"0\"}[1m]))",
     "legendFormat": "grpc_status={{grpc_status}}"
    }
   ]
  },
  {
   "title": "gRPC Request Time ( seconds )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
   "targets": [
    {
     "expr": "sum by(instance) (max_over_time(grpc_service_request_duration_seconds{pod=~\"kaldb?.+\",http_status=\"200\",kaldb_cluster_name=\"${cluster}\", kaldb_component=\"index\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Index message failures",
   "type": "timeseries",
   "description": "TBD",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Cache Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunk Evictions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum by (replicaset) (increase(chunk_eviction_timer_seconds_count{successful=\"true\"}[5m]))",
       "legendFormat": "success-evict-{{replicaset}}"
      },
      {
       "expr": "sum by (replicaset) (increase(chunk_assignment_timer_seconds_count{successful=\"false\"}[5m]))",
       "legendFormat": "failed-evict-{{replicaset}}"
      }
     ]
    },
    {
     "title": "Chunk Assignments",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "targets": [
      {
       "expr": "sum by (replicaset) (increase(chunk_assignment_timer_seconds_count{successful=\"true\"}[5m]))",
       "legendFormat": "{{replicaset}}-success"
      },
      {
       "expr": "sum by (replicaset) (increase(chunk_assignment_timer_seconds_count{successful=\"false\"}[5m]))",
       "legendFormat": "{{replicaset}}-failed"
      }
     ]
    },
    {
     "title": "Chunk Eviction Duration (seconds)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "rate(chunk_eviction_timer_seconds_sum[1m]) / rate(chunk_eviction_timer_seconds_count[1m])"
      }
     ]
    },
    {
     "title": "Chunk Assignment Duration (seconds)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": "rate(chunk_assignment_timer_seconds_sum[1m]) / rate(chunk_assignment_timer_seconds_count[1m])"
      }
     ]
    },
    {
     "title": "gRPC Request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"cache\"}[1m]))",
       "legendFormat": "grpc_status={{grpc_status}}"
      }
     ]
    },
    {
     "title": "gRPC Request Time ( seconds )",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
     "targets": [
      {
       "expr": "sum by(instance) (max_over_time(grpc_service_request_duration_seconds{pod=~\"kaldb?.+\",http_status=\"200\",kaldb_cluster_name=\"${cluster}\", kaldb_component=\"cache\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replica Assignments",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by (replicaset) (increase(replica_assign_succeeded_total{kaldb_cluster_name=\"${cluster}\"}[5m]))",
       "legendFormat": "replica_assign_succeeded-{{replicaset}}"
      },
      {
       "expr": "sum by (replicaset) (increase(replica_assign_insufficient_capacity_total{kaldb_cluster_name=\"${cluster}\"}[5m]))",
       "legendFormat": "replica_assign_insufficient_capacity-{{replicaset}}"
      }
     ]
    },
    {
     "title": "Replica Evictions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "targets": [
      {
       "expr": "sum by (replicaset) (increase(replica_mark_evict_succeeded_total{kaldb_cluster_name=\"${cluster}\"}[5m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum by (replicaset) (increase(replica_mark_evict_failed_total{kaldb_cluster_name=\"${cluster}\"}[5m]))",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Replica Assignment Capacity",
     "type": "timeseries",
     "description": "Available slots over time, positive is surplus capacity negative is insufficient capacity",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "targets": [
      {
       "expr": "sum by (replicaset) (sum_over_time(replica_assign_available_capacity{kaldb_cluster_name=\"${cluster}\",kaldb_component=\"manager\"}[1m]) / count_over_time(replica_assign_available_capacity{kaldb_cluster_name=\"${cluster}\",kaldb_component=\"manager\"}[1m]))",
       "legendFormat": "replica_assign_available_capacity"
      }
     ]
    },
    {
     "title": "Snapshot Delete (seconds)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "rate(snapshot_delete_timer_seconds_sum[1m]) / rate(snapshot_delete_timer_seconds_count[1m])"
      }
     ]
    },
    {
     "title": "Snapshot Delete",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum by (replicaset) (increase(snapshot_delete_success_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"manager\"}[1m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum by (replicaset) (increase(snapshot_delete_failed_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"manager\"}[1m]))",
       "legendFormat": "failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Query nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC Request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum by (grpc_status) (rate(grpc_service_requests_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"query\"}[1m]))",
       "legendFormat": "grpc_status={{grpc_status}}"
      }
     ]
    },
    {
     "title": "gRPC Request Time ( seconds )",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "sum by(instance) (max_over_time(grpc_service_request_duration_seconds{pod=~\"kaldb?.+\",http_status=\"200\",kaldb_cluster_name=\"${cluster}\", kaldb_component=\"query\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Blocking Task Executor Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "expr": "sum by(instance) (max_over_time(armeria_executor_pool_size_threads{pod=~\"kaldb?.+\", kaldb_cluster_name=\"${cluster}\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Recovery nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Recovery status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum(recovery_node_assignment_failed_total{kaldb_cluster_name=\"${cluster}\",kaldb_component=\"recovery\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(recovery_node_assignment_received_total{kaldb_cluster_name=\"${cluster}\",kaldb_component=\"recovery\"})",
     "legendFormat": "received"
    },
    {
     "expr": "sum(recovery_node_assignment_success_total{kaldb_cluster_name=\"${cluster}\",kaldb_component=\"recovery\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Current Chunk Doc Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (max_over_time(live_messages_indexed{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"recovery\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Chunk Raw Bytes Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (max_over_time(live_bytes_indexed{kaldb_cluster_name=\"$cluster\",kaldb_component=\"recovery\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recovery Nodes Records Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(records_received_total{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"recovery\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recovery Rollovers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(kaldb_cluster_name) (increase(rollovers_completed_total{kaldb_cluster_name=\"$cluster\",kaldb_component=\"recovery\"}[5m]))",
     "legendFormat": "recovery-completed"
    },
    {
     "expr": "sum by(kaldb_cluster_name) (increase(rollovers_failed_total{kaldb_cluster_name=\"$cluster\",kaldb_component=\"recovery\"}[5m]))",
     "legendFormat": "recover-failed"
    }
   ]
  },
  {
   "title": "Active recovery node count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count (max_over_time(live_messages_indexed{kaldb_cluster_name=\"${cluster}\", kaldb_component=\"recovery\"}[1m]) > 0)"
    }
   ]
  },
  {
   "title": "Zookeeper Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metadata store writes by component",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 114 },
     "targets": [
      {
       "expr": "sum by (kaldb_component) (rate(metadata_write_total{kaldb_cluster_name=\"${cluster}\"}[1m]))",
       "legendFormat": "{{kaldb_component}}"
      }
     ]
    },
    {
     "title": "Metadata store reads by component",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 114 },
     "targets": [
      {
       "expr": "sum by (kaldb_component) (rate(metadata_read_total{kaldb_cluster_name=\"${cluster}\"}[1m]))",
       "legendFormat": "{{kaldb_component}}"
      }
     ]
    },
    {
     "title": "Metadatastore failures by component",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 114 },
     "targets": [
      {
       "expr": "sum by (kaldb_component) (rate(metadata_failed_total{kaldb_cluster_name=\"${cluster}\"}[1m]))",
       "legendFormat": "{{kaldb_component}}"
      }
     ]
    },
    {
     "title": "ZK failures by component",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 114 },
     "targets": [
      {
       "expr": "sum by (kaldb_component) (rate(metadata_failed_zk_total{kaldb_cluster_name=\"${cluster}\"}[1m]))",
       "legendFormat": "{{kaldb_component}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Memory Usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{pod=~\"kaldb.+${cluster}.+\", container=~\"kaldb?.+\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Average CPU Time by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "targets": [
      {
       "expr": "avg(irate(container_cpu_usage_seconds_total{pod=~\"kaldb.+${cluster}.+\",container=~\"kaldb-?.+\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Average Network Bytes by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(irate(container_network_transmit_packets_total{pod=~\"kaldb.+${cluster}.+\"}[1m])) by (pod)",
       "legendFormat": "tx {{pod}}"
      },
      {
       "expr": "avg(irate(container_network_receive_bytes_total{pod=~\"kaldb.+${cluster}.+\"}[1m])) by (pod)",
       "legendFormat": "rx {{pod}}"
      }
     ]
    },
    {
     "title": "Avg PPS by Container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(irate(container_network_transmit_packets_total{pod=~\"kaldb.+${cluster}.+\"}[1m])) by (pod)",
       "legendFormat": "tx {{pod}}"
      },
      {
       "expr": "avg(irate(container_network_transmit_packets_total{pod=~\"kaldb.+${cluster}.+\"}[1m])) by (pod)",
       "legendFormat": "rx {{pod}}"
      }
     ]
    },
    {
     "title": "Total PPS by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_total{pod=~\"kaldb.+${cluster}.+\"}[1m])) by (pod)",
       "legendFormat": "tx {{pod}}"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{pod=~\"kaldb.+${cluster}.+\"}[1m])) by (pod)",
       "legendFormat": "rx {{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Kafka Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Records ( Preprocessor vs Indexer vs lucene  )",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kaldb_cluster_name) (irate(records_received_total{kaldb_cluster_name=\"${cluster}\"}[1m]))",
     "legendFormat": "{{kaldb_cluster_name}}-indexer"
    },
    {
     "expr": "sum by (kaldb_cluster_name) (irate(messages_received_total{kaldb_cluster_name=\"${cluster}\"}[1m]))",
     "legendFormat": "{{kaldb_cluster_name}}-lucene"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{cluster=\"events2-proxy\", topic=\"kaldb_preprocessor_1\"}[1m]))",
     "legendFormat": "preprocessor-envoy"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{cluster=\"events2-api-log\", topic=\"kaldb_preprocessor\"}[1m]))",
     "legendFormat": "preprocessor-api-log"
    }
   ]
  },
  {
   "title": "Kafka Records Failed Per Min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(replicaset) (irate(records_failed_total[1m]) * 60)",
     "legendFormat": "failed_{{replicaset}}"
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Pause",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_max{instance=~'kaldb-.*'}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}