openapi: 3.0.0
info:
  title: Query Node API
  version: alpha
paths:
  # Examples omitted pending https://youtrack.jetbrains.com/issue/WRS-3340
  /:
    get:
      summary: Cluster metadata
      description: |
        Describes the cluster version and supported Lucene version. Used for cluster feature discovery.
      responses:
        '200':
          description: Cluster metadata
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: object
                    properties:
                      distribution:
                        description: "'astra'"
                        type: string
                      number:
                        description: "Release version of cluster"
                        type: string
                      lucene_version:
                        description: "Lucene index/query version of cluster"
                        type: string
  /_msearch:
    post:
      summary: Bulk search
      description: | 
        Primary search API for the Astra cluster. Supports multiple queries in a single request by adding additional 
        header and body pairs.
      requestBody:
        description: Bulk search
        required: true
        content:
          application/ndjson:
            schema:
              type: object
              properties:
                '{header}':
                  type: object
                  description: "Newline delineated JSON header"
                  required: true
                  properties:
                    index:
                      description: "Index name to search"
                      type: string
                      required: true
                '{body}':
                  type: object
                  description: "Newline delineated JSON body"
                  required: true
                  properties:
                    size:
                      description: "Amount of results to return"
                      type: integer
                      required: true
                      minimum: 0
                    query:
                      description: "Query object"
                      type: object
                      properties:
                        bool:
                          type: object
                          properties:
                            filter:
                              type: array
                              items:
                                type: object
                                properties:
                                  range:
                                    type: object
                                    properties:
                                      '{timefield}':
                                        properties:
                                          gte:
                                            type: number
                                            required: true
                                          lte:
                                            type: number
                                            required: true
                                  query_string:
                                    type: object
                                    properties:
                                      query:
                                        type: string
                    aggs:
                      type: object
                      description: "Requested search aggregations"
                      properties:
                        '{name}':
                          type: object
                          description: |
                            Keyed by name of requested aggregation. See aggregations docs for full list of supported
                            aggregation requests.
                          properties:
                            aggs:
                              type: object
                              description: "Nested aggregations"
                            auto_date_histogram:
                              type: object
                            avg:
                              type: object
                            cumulative_sum:
                              type: object
                            date_histogram:
                              type: object
                            derivative:
                              type: object
                            extended_stats:
                              type: object
                            filters:
                              type: object
                            histogram:
                              type: object
                            max:
                              type: object
                            min:
                              type: object
                            moving_avg:
                              type: object
                            moving_fn:
                              type: object
                            percentiles:
                              type: object
                            sum:
                              type: object
                            terms:
                              type: object
                            cardinality:
                              type: object
                            value_count:
                              type: object
      responses:
        '200':
          description: Bulk search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  took:
                    type: integer
                  responses:
                    type: array
                    items:
                      type: object
                      properties:
                        took:
                          type: integer
                        timed_out:
                          type: boolean
                        _shards:
                          type: object
                          properties:
                            failed:
                              type: number
                            total:
                              type: number
                        _debug:
                          type: object
                        hits:
                          type: object
                          properties:
                            total:
                              type: object
                              properties:
                                value:
                                  type: number
                                relation:
                                  type: string
                            max_score:
                              type: object
                            hits:
                              type: array
                              items:
                                type: object
                        aggregations:
                          type: object
                          properties:
                            '{name}':
                              type: object
                        status:
                          type: number
                  _debug:
                    type: object
                    properties:
                      traceId:
                        type: string
                        description: "Trace ID for the returned result"


  /{indexName}/_mapping:
    get:
      summary: Field mapping
      parameters:
        - in: path
          name: indexName
          schema:
            type: string
          required: true
          description: Index name as set in cluster
      responses:
        '200':
          description: Index field mappings
          content:
            application/json:
              schema:
                type: object
                properties:
                  '{indexName}':
                    type: object
                    properties:
                      mappings:
                        type: object
                        properties:
                          type: object
                          properties:
                            type: object
                            properties:
                              type: object
                              '{fieldName}':
                                properties:
                                  'type':
                                    type: string
                                    description: "One of valid schema types"
                                    enum: [ keyword, text, ip, date, boolean, double, float, half_float, integer, long, scaled_long, short, byte, binary]


