name: Code Review

on:
  pull_request:
    types:
      - opened

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: fxchen/code-review@v0.2.9-alpha
        with:
          model: 'gpt-4-32k'
          include-full-files: 'true'
          openai-key: ${{ secrets.OPENAI_API_KEY }}
