name: Code Review

on:
  pull_request:
    types:
      - opened

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: fxchen/code-review@v0.2.5-alpha
        with:
          model: 'gpt-3.5-turbo-16k'
          openai-key: ${{ secrets.OPENAI_API_KEY }}
