# This workflow will tag all commits to the default branch with 'nightly'
# For more information see: https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#update-a-reference

name: Tag Default Branch Commits with Nightly

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 1

    steps:
    - uses: actions/checkout@v4
    - name: Update nigtly tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.updateRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/nightly',
            force: true,
            sha: context.sha
          })
